### ISSUE TITLE
Bug - About page corrections

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-android#95] opened 2022-04-13 08:01 UTC
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

Huawei Mate 20 Pro

### OS Version

10

### App version

1.0.1

### Describe the issue

* the Legal notice and the Privacy policy pages do not work when used in light mode
* in the Privacy policy pages, at the end of the text, the date is missing

### Expected Behavior

* the background of the text should be white
* use today's date for now

**Comment by florentmaitre** [comment] 2022-06-01 15:58
> the Legal notice and the Privacy policy pages do not work when used in light mode

First issue is a duplicate of #131

**Closed** 2022-06-02 09:55 UTC
Labels: bug, triage

**Comment by B3nz01d** [comment] 2022-06-16 12:00
Ok now
